# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: playCommonCiCd

on:
  push:
    branches: [ "main" ]

jobs:
  generate-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Bump version and push tag
      id: tag_bump
      uses: anothrNick/github-tag-action@1.56.0
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        INITIAL_VERSION: 1.0.16
        DEFAULT_BUMP: patch
        
    outputs:
      new_version: ${{steps.tag_bump.outputs.new_tag}}    
    
  package-and-publish-package:
    runs-on: ubuntu-latest
    needs: generate-version
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Pack
      run: | 
        dotnet pack src/Play.Common \
        --configuration Release \
        -p:PackageVersion=${{needs.generate-version.outputs.new_version}} \
        -p:RepositoryUrl=https://github.com/${{github.repository_owner}}/Play.Common \
        -o packages
  
    - name: Publish
      run: | 
        dotnet nuget push packages/*.nupkg \
        --api-key ${{secrets.NUGET_WRITE_PAT}} \
        --source https://nuget.pkg.github.com/${{github.repository_owner}}/index.json
